// app/layout.tsx or app/RootLayout.tsx

import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.scss"; // Import the global styles

export const metadata: Metadata = {
  title: "Fowzi Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider defaultTheme="light">{children}</ThemeProvider>
      </body>
    </html>
  );
}