// app/layout.tsx or app/RootLayout.tsx (if using Next.js 13)

import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.scss";
import gellery from "@/components/font/font";

export const metadata: Metadata = {
  title: "Fowzi Media",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${gellery.variable}`}>  {/* Apply font class */}
        <ThemeProvider defaultTheme="light">{children}</ThemeProvider>
      </body>
    </html>
  );
}
